import { ProductCategory, ProductItem } from '@/types/shopping';

const SHOPPING_CATEGORIES_RAW: ProductCategory[] = [
  {
    id: 'pcat_veg',
    name: 'Fresh Fruits & Vegetables',
    slug: 'fresh-fruits-vegetables',
    iconName: 'Carrot',
    itemCount: 0,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 'pcat_meat',
    name: 'Meat, Fish & Seafood',
    slug: 'meat-fish-seafood',
    iconName: 'Beef',
    itemCount: 0,
    image: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 'pcat_dairy',
    name: 'Dairy, Eggs & Bakery',
    slug: 'dairy-eggs-bakery',
    iconName: 'Milk',
    itemCount: 0,
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 'pcat_groc',
    name: 'Household & Daily Cleaning',
    slug: 'household-daily-cleaning',
    iconName: 'ShoppingBag',
    itemCount: 0,
    image: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 'pcat_care',
    name: 'Personal Care & Beauty',
    slug: 'personal-care-beauty',
    iconName: 'Sparkles',
    itemCount: 0,
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 'pcat_snack',
    name: 'Snacks, Beverages & Drinks',
    slug: 'snacks-beverages-drinks',
    iconName: 'Cookie',
    itemCount: 0,
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400&auto=format&fit=crop&q=80',
  },
];

export const ALL_PRODUCTS: ProductItem[] = [
  {
    id: 'prod_1',
    title: 'Organic Farm Fresh Tomatoes',
    slug: 'organic-tomatoes',
    categorySlug: 'vegetables',
    categoryName: 'Fresh Vegetables',
    shopName: 'Green Harvest DOHS Bazaar',
    price: 65,
    originalPrice: 85,
    unit: '1 kg',
    rating: 4.8,
    reviewCount: 142,
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80',
    ],
    stock: 50,
    isOrganic: true,
    badge: '23% OFF',
    discountPercentage: 23,
    description: 'Farm-fresh organic red tomatoes sourced directly from Savar organic farms. Crisp, firm, and naturally rich in Lycopene and Vitamin C.',
    nutritionInfo: {
      calories: '18 kcal per 100g',
      protein: '0.9 g',
      carbs: '3.9 g',
      fat: '0.2 g',
    },
    reviews: [
      {
        id: 'pr_1',
        userName: 'Sharmin Sultana',
        rating: 5,
        date: '1 day ago',
        comment: 'Super fresh red tomatoes delivered in 30 minutes to DOHS! Very satisfied.',
      },
    ],
  },
  {
    id: 'prod_2',
    title: 'Pure Premium Mustard Oil (Shorishar Tel)',
    slug: 'pure-mustard-oil',
    categorySlug: 'oil',
    categoryName: 'Oil & Spices',
    shopName: 'Deshi Organics DOHS',
    price: 240,
    originalPrice: 280,
    unit: '1 Liter (Glass Bottle)',
    rating: 4.9,
    reviewCount: 230,
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&auto=format&fit=crop&q=80',
    stock: 35,
    badge: 'Best Seller',
    discountPercentage: 14,
    description: 'Traditional cold-pressed Ghani mustard oil extracted from pure yellow mustard seeds. Rich aroma and pungent flavor.',
    reviews: [],
  },
  {
    id: 'prod_3',
    title: 'Fresh Deshi Broiler Chicken (Cleaned & Cut)',
    slug: 'fresh-broiler-chicken',
    categorySlug: 'meat',
    categoryName: 'Meat & Poultry',
    shopName: 'Halal Meat Corner DOHS',
    price: 210,
    originalPrice: 230,
    unit: '1 kg (Cleaned)',
    rating: 4.7,
    reviewCount: 98,
    image: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=600&auto=format&fit=crop&q=80',
    stock: 20,
    badge: 'Daily Cut',
    description: '100% Halal slaughtered fresh chicken. Dressed, skinless, cleaned, and medium curry cut.',
    reviews: [],
  },
  {
    id: 'prod_4',
    title: 'Nazirshail Premium Aromatic Rice',
    slug: 'nazirshail-rice',
    categorySlug: 'rice',
    categoryName: 'Rice & Grains',
    shopName: 'Bhai Bhai Store DOHS',
    price: 82,
    originalPrice: 90,
    unit: '1 kg (Pack)',
    rating: 4.85,
    reviewCount: 310,
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80',
    stock: 120,
    badge: 'Top Quality',
    description: 'Extra-long grain premium Nazirshail rice from Dinajpur. Non-sticky, delicate aroma.',
    reviews: [],
  },
  {
    id: 'prod_5',
    title: 'Sweet Honey Mangoes (Himsagar)',
    slug: 'himsagar-mangoes',
    categorySlug: 'fruits',
    categoryName: 'Fresh Fruits',
    shopName: 'Rajshahi Fruit Bazaar',
    price: 130,
    originalPrice: 160,
    unit: '1 kg',
    rating: 4.95,
    reviewCount: 450,
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=600&auto=format&fit=crop&q=80',
    stock: 40,
    isOrganic: true,
    badge: 'Seasonal Deal',
    discountPercentage: 18,
    description: 'Chemical-free naturally ripened Himsagar mangoes directly from Rajshahi orchards.',
    reviews: [],
  },
  {
    id: 'prod_6',
    title: 'Pasteurized Full Cream Milk',
    slug: 'pasteurized-full-cream-milk',
    categorySlug: 'dairy',
    categoryName: 'Milk & Dairy',
    shopName: 'Dairy Fresh Outlet DOHS',
    price: 90,
    unit: '1 Liter',
    rating: 4.9,
    reviewCount: 180,
    image: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=600&auto=format&fit=crop&q=80',
    stock: 60,
    description: '100% pure pasteurized full-cream cow milk. Chilled and delivered fresh every morning.',
    reviews: [],
  },
  {
    id: 'prod_7',
    title: 'Fresh Padma Ilish (Hilsha Fish)',
    slug: 'padma-hilsha-fish',
    categorySlug: 'fish',
    categoryName: 'Fresh Water Fish',
    shopName: 'Chandpur Hilsha Hub',
    price: 1400,
    originalPrice: 1600,
    unit: '1 kg (Whole Fish)',
    rating: 4.92,
    reviewCount: 210,
    image: 'https://images.unsplash.com/photo-1534942519507-769d4679447d?w=600&auto=format&fit=crop&q=80',
    stock: 15,
    badge: 'Authentic Padma',
    description: 'Authentic Padma River Hilsha fish with rich oil content. Scaled and cleaned upon request.',
    reviews: [],
  },
  {
    id: 'prod_8',
    title: 'Crispy Butter Cookies & Bakery Biscuit',
    slug: 'butter-cookies',
    categorySlug: 'snacks',
    categoryName: 'Snacks & Bakery',
    shopName: 'DOHS Artisan Bakery',
    price: 180,
    originalPrice: 200,
    unit: '300g Pack',
    rating: 4.75,
    reviewCount: 85,
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&auto=format&fit=crop&q=80',
    stock: 45,
    description: 'Oven-fresh handcrafted butter cookies made with real creamery butter and vanilla bean.',
    reviews: [],
  },

  // ── "For You" Section Products ──
  {
    id: 'fy_1',
    title: 'Spanish Extra Virgin Olive Oil (250ml)',
    slug: 'spanish-extra-virgin-olive-oil-250ml',
    categorySlug: 'oil',
    categoryName: 'Oil & Condiments',
    shopName: 'DOHS Import Store',
    price: 790,
    originalPrice: 990,
    unit: '250ml Glass Bottle',
    rating: 4.9,
    reviewCount: 18,
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&auto=format&fit=crop&q=80',
    stock: 30,
    badge: '-20%',
    description: 'Cold-pressed 100% Spanish extra virgin olive oil. Rich in antioxidants and healthy omega fats.',
    reviews: [],
  },
  {
    id: 'fy_2',
    title: 'Osufi Nourishing Repair Serum (50ml)',
    slug: 'osufi-repair-serum',
    categorySlug: 'health-beauty',
    categoryName: 'Health & Beauty',
    shopName: 'Beauty Care DOHS',
    price: 680,
    originalPrice: 980,
    unit: '50ml Bottle',
    rating: 4.8,
    reviewCount: 5,
    image: 'https://images.unsplash.com/photo-1608248597263-00079996577f?w=600&auto=format&fit=crop&q=80',
    stock: 25,
    badge: '-30%',
    description: 'Deep hydrating facial serum for radiant skin glow and repair.',
    reviews: [],
  },
  {
    id: 'fy_3',
    title: 'Indian Fair Look Ayurvedic Lotion',
    slug: 'indian-fair-look-lotion',
    categorySlug: 'health-beauty',
    categoryName: 'Health & Beauty',
    shopName: 'Organic Care Hub',
    price: 990,
    originalPrice: 1590,
    unit: '100g Pack',
    rating: 4.7,
    reviewCount: 1,
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80',
    stock: 15,
    badge: '-37%',
    description: 'Natural herbal glow fairness lotion made with pure ayurvedic extracts.',
    reviews: [],
  },
  {
    id: 'fy_4',
    title: 'Sensing Wireless Desk Phone Stand BT',
    slug: 'sensing-wireless-phone-stand-bt',
    categorySlug: 'gadgets',
    categoryName: 'Gadgets & Accessories',
    shopName: 'Tech Hub DOHS',
    price: 1150,
    originalPrice: 1500,
    unit: '1 Unit',
    rating: 4.8,
    reviewCount: 2,
    image: 'https://images.unsplash.com/photo-1586105251261-72a756497a11?w=600&auto=format&fit=crop&q=80',
    stock: 20,
    badge: '-23%',
    description: 'Smart sensing automatic phone holder and fast wireless charger.',
    reviews: [],
  },
  {
    id: 'fy_5',
    title: '3-in-1 Foldable Mobile Phone Bracket',
    slug: '3-in-1-mobile-phone-bracket',
    categorySlug: 'gadgets',
    categoryName: 'Gadgets & Accessories',
    shopName: 'Tech Hub DOHS',
    price: 590,
    originalPrice: 900,
    unit: '1 Unit',
    rating: 4.9,
    reviewCount: 7,
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&auto=format&fit=crop&q=80',
    stock: 40,
    badge: '-34%',
    description: 'Compact 360-degree rotating metal phone stand bracket.',
    reviews: [],
  },
  {
    id: 'fy_6',
    title: 'Coffee Frother Handheld Electric Whisk',
    slug: 'coffee-frother-electric-whisk',
    categorySlug: 'household',
    categoryName: 'Kitchen Appliances',
    shopName: 'Kitchen Essentials DOHS',
    price: 890,
    originalPrice: 1290,
    unit: '1 Unit',
    rating: 4.9,
    reviewCount: 14,
    image: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=600&auto=format&fit=crop&q=80',
    stock: 35,
    badge: '-31%',
    description: 'High-speed battery powered foam maker for cappuccino and lattes.',
    reviews: [],
  },
  {
    id: 'fy_7',
    title: 'Hot Water Bag 2 Liter Rubber Capacity',
    slug: 'hot-water-bag-2L',
    categorySlug: 'health-beauty',
    categoryName: 'Health & Wellness',
    shopName: 'Pharma Care DOHS',
    price: 239,
    originalPrice: 380,
    unit: '2L Bag',
    rating: 4.6,
    reviewCount: 4,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
    stock: 50,
    badge: '-37%',
    description: 'Durable leak-proof rubber hot water bag for muscle pain relief.',
    reviews: [],
  },
  {
    id: 'fy_8',
    title: 'Ergonomic Executive Office Boss Chair',
    slug: 'executive-office-boss-chair',
    categorySlug: 'household',
    categoryName: 'Furniture & Decor',
    shopName: 'DOHS Leather Furniture',
    price: 6000,
    originalPrice: 7000,
    unit: '1 Chair',
    rating: 5.0,
    reviewCount: 8,
    image: 'https://images.unsplash.com/photo-1580481072645-022f9a6d1276?w=600&auto=format&fit=crop&q=80',
    stock: 10,
    badge: '-14%',
    description: 'Heavy duty high-back leather executive chair with lumbar support.',
    reviews: [],
  },
  {
    id: 'fy_9',
    title: 'Watsons Green Tea Body Wash (1000ml)',
    slug: 'watsons-green-tea-body-wash',
    categorySlug: 'health-beauty',
    categoryName: 'Personal Care',
    shopName: 'DOHS Import Mart',
    price: 1700,
    originalPrice: 1800,
    unit: '1000ml Bottle',
    rating: 4.9,
    reviewCount: 22,
    image: 'https://images.unsplash.com/photo-1585238342024-78d387f4a707?w=600&auto=format&fit=crop&q=80',
    stock: 20,
    badge: '-5%',
    description: 'Refreshingly scented green tea gel body wash with moisturizing lotion.',
    reviews: [],
  },
  {
    id: 'fy_10',
    title: 'Deep Tissue Mini Muscle Massage Gun',
    slug: 'deep-tissue-massage-gun',
    categorySlug: 'health-beauty',
    categoryName: 'Health & Wellness',
    shopName: 'Fitness Hub DOHS',
    price: 1450,
    originalPrice: 1800,
    unit: '1 Kit',
    rating: 4.8,
    reviewCount: 12,
    image: 'https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=600&auto=format&fit=crop&q=80',
    stock: 15,
    badge: '-19%',
    description: 'Rechargeable percussion massage gun for athletic muscle recovery.',
    reviews: [],
  },

  // ── Mega Menu Flyout Products ──
  {
    id: 'prod_m1',
    title: 'Plant-Based Nuggets',
    slug: 'plant-based-nuggets',
    categorySlug: 'meat',
    categoryName: 'Vegan Meat & Poultry',
    shopName: 'Woodmart Green Food',
    price: 280,
    originalPrice: 320,
    unit: 'pack',
    rating: 4.5,
    reviewCount: 10,
    image: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=600&auto=format&fit=crop&q=80',
    stock: 50,
    description: 'Crispy plant-based protein nuggets made from non-GMO soy and wheat.',
    reviews: [],
  },
  {
    id: 'prod_m2',
    title: 'Crispy Jack Nuggets',
    slug: 'crispy-jack-nuggets',
    categorySlug: 'meat',
    categoryName: 'Vegan Meat & Poultry',
    shopName: 'Woodmart Green Food',
    price: 240,
    originalPrice: 280,
    unit: 'pack',
    rating: 4.9,
    reviewCount: 15,
    image: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=600&auto=format&fit=crop&q=80',
    stock: 40,
    description: 'Delicious jackfruit plant-based patty nuggets.',
    reviews: [],
  },
  {
    id: 'prod_m3',
    title: 'Rice Nuggets',
    slug: 'rice-nuggets',
    categorySlug: 'meat',
    categoryName: 'Vegan Meat & Poultry',
    shopName: 'Woodmart Green Food',
    price: 180,
    unit: 'pack',
    rating: 4.6,
    reviewCount: 8,
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=600&auto=format&fit=crop&q=80',
    stock: 35,
    description: 'Golden crispy rice nuggets with herbs.',
    reviews: [],
  },
];

export const SHOPPING_CATEGORIES: ProductCategory[] = SHOPPING_CATEGORIES_RAW.map((cat) => {
  const realCount = ALL_PRODUCTS.filter(
    (p) => p.categorySlug === cat.slug || (cat.slug === 'groceries' && p.categorySlug === 'oil')
  ).length;

  return {
    ...cat,
    itemCount: realCount,
  };
});

export const DAILY_DEALS_PRODUCTS = ALL_PRODUCTS.slice(0, 6);

/**
 * Universal lookup helper to find ANY product by its slug or ID cleanly!
 * Eliminates the bug where clicking different products routed to the same fallback product.
 */
export function getProductBySlugOrId(slugOrId: string): ProductItem {
  const decoded = decodeURIComponent(slugOrId).trim().toLowerCase();

  const found = ALL_PRODUCTS.find((p) => {
    return (
      p.slug.toLowerCase() === decoded ||
      p.id.toLowerCase() === decoded ||
      p.title.toLowerCase().replace(/[^a-z0-9]/g, '-') === decoded
    );
  });

  if (found) return found;

  // Fallback: Construct a clean, dynamic ProductItem for unknown slugs
  const cleanTitle = decoded
    .replace(/^prod_/, '')
    .replace(/^fy_/, '')
    .replace(/^cat_/, '')
    .replace(/-/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase());

  let fallbackImage = 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=600&auto=format&fit=crop&q=80';
  if (decoded.includes('nugget') || decoded.includes('chicken') || decoded.includes('meat') || decoded.includes('beef')) {
    fallbackImage = 'https://images.unsplash.com/photo-1562967914-608f82629710?w=600&auto=format&fit=crop&q=80';
  } else if (decoded.includes('milk') || decoded.includes('egg') || decoded.includes('dairy') || decoded.includes('cheese')) {
    fallbackImage = 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&auto=format&fit=crop&q=80';
  } else if (decoded.includes('tea') || decoded.includes('juice') || decoded.includes('drink') || decoded.includes('water') || decoded.includes('beverage')) {
    fallbackImage = 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&auto=format&fit=crop&q=80';
  } else if (decoded.includes('samosa') || decoded.includes('snack') || decoded.includes('biscuit') || decoded.includes('cookie')) {
    fallbackImage = 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&auto=format&fit=crop&q=80';
  } else if (decoded.includes('rice') || decoded.includes('grain') || decoded.includes('dal') || decoded.includes('flour')) {
    fallbackImage = 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80';
  } else if (decoded.includes('fish') || decoded.includes('shrimp') || decoded.includes('prawn')) {
    fallbackImage = 'https://images.unsplash.com/photo-1534942519507-769d4679447d?w=600&auto=format&fit=crop&q=80';
  } else if (decoded.includes('fruit') || decoded.includes('apple') || decoded.includes('mango') || decoded.includes('banana')) {
    fallbackImage = 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=600&auto=format&fit=crop&q=80';
  }

  return {
    id: slugOrId,
    title: cleanTitle.length > 2 ? cleanTitle : 'Premium Grocery Item',
    slug: slugOrId,
    categorySlug: 'groceries',
    categoryName: 'Daily Essentials',
    shopName: 'Savar DOHS Market',
    price: 350,
    originalPrice: 400,
    unit: '1 Pack / Unit',
    rating: 4.8,
    reviewCount: 24,
    image: fallbackImage,
    stock: 30,
    description: `Fresh, high-grade ${cleanTitle} sourced directly from verified DOHS suppliers. Guaranteed delivery within 45 minutes.`,
    reviews: [],
  };
}
