import { ProductCategory, ProductItem } from '@/types/shopping';

const SHOPPING_CATEGORIES_RAW: ProductCategory[] = [
  {
    id: 'pcat_veg',
    name: 'Fresh Vegetables',
    slug: 'vegetables',
    iconName: 'Carrot',
    itemCount: 0,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 'pcat_fruit',
    name: 'Fresh Fruits',
    slug: 'fruits',
    iconName: 'Apple',
    itemCount: 0,
    image: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 'pcat_meat',
    name: 'Meat & Poultry',
    slug: 'meat',
    iconName: 'Beef',
    itemCount: 0,
    image: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 'pcat_fish',
    name: 'Fresh Water Fish',
    slug: 'fish',
    iconName: 'Fish',
    itemCount: 0,
    image: 'https://images.unsplash.com/photo-1534942519507-769d4679447d?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 'pcat_dairy',
    name: 'Milk & Dairy',
    slug: 'dairy',
    iconName: 'Milk',
    itemCount: 0,
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 'pcat_groc',
    name: 'Daily Groceries & Essentials',
    slug: 'groceries',
    iconName: 'ShoppingBag',
    itemCount: 0,
    image: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 'pcat_rice',
    name: 'Rice & Grains',
    slug: 'rice',
    iconName: 'Wheat',
    itemCount: 0,
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 'pcat_snack',
    name: 'Snacks & Bakery',
    slug: 'snacks',
    iconName: 'Cookie',
    itemCount: 0,
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400&auto=format&fit=crop&q=80',
  },
];

export const ALL_PRODUCTS: ProductItem[] = [
  {
    id: 'prod_1',
    title: 'Organic Farm Fresh Tomatoes',
    slug: 'organic-tomatoes',
    categorySlug: 'vegetables',
    categoryName: 'Fresh Vegetables',
    shopName: 'Green Harvest DOHS Bazaar',
    price: 65,
    originalPrice: 85,
    unit: '1 kg',
    rating: 4.8,
    reviewCount: 142,
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80',
    ],
    stock: 50,
    isOrganic: true,
    badge: '23% OFF',
    discountPercentage: 23,
    description: 'Farm-fresh organic red tomatoes sourced directly from Savar organic farms. Crisp, firm, and naturally rich in Lycopene and Vitamin C. Harvested daily for maximum freshness.',
    nutritionInfo: {
      calories: '18 kcal per 100g',
      protein: '0.9 g',
      carbs: '3.9 g',
      fat: '0.2 g',
    },
    reviews: [
      {
        id: 'pr_1',
        userName: 'Sharmin Sultana',
        rating: 5,
        date: '1 day ago',
        comment: 'Super fresh red tomatoes delivered in 30 minutes to Mohakhali DOHS! Very satisfied.',
      },
    ],
  },
  {
    id: 'prod_2',
    title: 'Pure Premium Mustard Oil (Shorishar Tel)',
    slug: 'pure-mustard-oil',
    categorySlug: 'oil',
    categoryName: 'Oil & Spices',
    shopName: 'Deshi Organics DOHS',
    price: 240,
    originalPrice: 280,
    unit: '1 Liter (Glass Bottle)',
    rating: 4.9,
    reviewCount: 230,
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&auto=format&fit=crop&q=80',
    stock: 35,
    badge: 'Best Seller',
    discountPercentage: 14,
    description: 'Traditional cold-pressed Ghani mustard oil extracted from pure yellow mustard seeds. Rich aroma and pungent flavor ideal for bhorta, fish curry, and traditional cooking.',
    nutritionInfo: {
      calories: '884 kcal per 100ml',
      fat: '100 g',
    },
    reviews: [],
  },
  {
    id: 'prod_3',
    title: 'Fresh Deshi Broiler Chicken (Cleaned & Cut)',
    slug: 'fresh-broiler-chicken',
    categorySlug: 'meat',
    categoryName: 'Meat & Poultry',
    shopName: 'Halal Meat Corner DOHS',
    price: 210,
    originalPrice: 230,
    unit: '1 kg (Cleaned)',
    rating: 4.7,
    reviewCount: 98,
    image: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=600&auto=format&fit=crop&q=80',
    stock: 20,
    badge: 'Daily Cut',
    description: '100% Halal slaughtered fresh chicken. Dressed, skinless, cleaned, and medium curry cut. Prepared fresh upon receiving your order.',
    reviews: [],
  },
  {
    id: 'prod_4',
    title: 'Nazirshail Premium Aromatic Rice',
    slug: 'nazirshail-rice',
    categorySlug: 'rice',
    categoryName: 'Rice & Grains',
    shopName: 'Bhai Bhai Store DOHS',
    price: 82,
    originalPrice: 90,
    unit: '1 kg (Pack)',
    rating: 4.85,
    reviewCount: 310,
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80',
    stock: 120,
    badge: 'Top Quality',
    description: 'Extra-long grain premium Nazirshail rice from Dinajpur. Non-sticky, delicate aroma, perfect for daily meals.',
    reviews: [],
  },
  {
    id: 'prod_5',
    title: 'Sweet Honey Mangoes (Himsagar)',
    slug: 'himsagar-mangoes',
    categorySlug: 'fruits',
    categoryName: 'Fresh Fruits',
    shopName: 'Rajshahi Fruit Bazaar',
    price: 130,
    originalPrice: 160,
    unit: '1 kg',
    rating: 4.95,
    reviewCount: 450,
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=600&auto=format&fit=crop&q=80',
    stock: 40,
    isOrganic: true,
    badge: 'Seasonal Deal',
    discountPercentage: 18,
    description: 'Chemical-free naturally ripened Himsagar mangoes directly from Rajshahi orchards. Extremely sweet pulp with minimal fiber.',
    reviews: [],
  },
  {
    id: 'prod_6',
    title: 'Pasteurized Full Cream Milk',
    slug: 'pasteurized-full-cream-milk',
    categorySlug: 'dairy',
    categoryName: 'Milk & Dairy',
    shopName: 'Dairy Fresh Outlet DOHS',
    price: 90,
    unit: '1 Liter',
    rating: 4.9,
    reviewCount: 180,
    image: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=600&auto=format&fit=crop&q=80',
    stock: 60,
    description: '100% pure pasteurized full-cream cow milk. Chilled and delivered fresh every morning.',
    reviews: [],
  },
  {
    id: 'prod_7',
    title: 'Fresh Padma Ilish (Hilsha Fish)',
    slug: 'padma-hilsha-fish',
    categorySlug: 'fish',
    categoryName: 'Fresh Water Fish',
    shopName: 'Chandpur Hilsha Hub',
    price: 1400,
    originalPrice: 1600,
    unit: '1 kg (Whole Fish)',
    rating: 4.92,
    reviewCount: 210,
    image: 'https://images.unsplash.com/photo-1534942519507-769d4679447d?w=600&auto=format&fit=crop&q=80',
    stock: 15,
    badge: 'Authentic Padma',
    description: 'Authentic Padma River Hilsha fish with rich oil content. Scaled and cleaned upon request.',
    reviews: [],
  },
  {
    id: 'prod_8',
    title: 'Crispy Butter Cookies & Bakery Biscuit',
    slug: 'butter-cookies',
    categorySlug: 'snacks',
    categoryName: 'Snacks & Bakery',
    shopName: 'DOHS Artisan Bakery',
    price: 180,
    originalPrice: 200,
    unit: '300g Pack',
    rating: 4.75,
    reviewCount: 85,
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&auto=format&fit=crop&q=80',
    stock: 45,
    description: 'Oven-fresh handcrafted butter cookies made with real creamery butter and vanilla bean.',
    reviews: [],
  },
];

export const SHOPPING_CATEGORIES: ProductCategory[] = SHOPPING_CATEGORIES_RAW.map((cat) => {
  const realCount = ALL_PRODUCTS.filter(
    (p) => p.categorySlug === cat.slug || (cat.slug === 'groceries' && p.categorySlug === 'oil')
  ).length;

  return {
    ...cat,
    itemCount: realCount,
  };
});

export const DAILY_DEALS_PRODUCTS = ALL_PRODUCTS.slice(0, 6);
