import { ServiceCategory, ServiceItem, ProviderProfile } from '@/types/service';

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: 'cat_ac',
    name: 'AC Service & Repair',
    slug: 'ac-service',
    iconName: 'Wind',
    description: 'Master servicing, gas refill, cooling repair & installation',
    popularCount: 1420,
    badge: 'Popular',
    colorBg: 'bg-blue-50 dark:bg-blue-950/40',
    colorText: 'text-blue-600 dark:text-blue-400',
  },
  {
    id: 'cat_elec',
    name: 'Electrician',
    slug: 'electrician',
    iconName: 'Zap',
    description: 'Wiring, circuit breaker repair, fan & light installation',
    popularCount: 2310,
    badge: 'Fast Response',
    colorBg: 'bg-amber-50 dark:bg-amber-950/40',
    colorText: 'text-amber-600 dark:text-amber-400',
  },
  {
    id: 'cat_plumb',
    name: 'Plumbing Service',
    slug: 'plumber',
    iconName: 'Droplet',
    description: 'Pipe leakage, sink install, water heater & basin repair',
    popularCount: 1890,
    colorBg: 'bg-cyan-50 dark:bg-cyan-950/40',
    colorText: 'text-cyan-600 dark:text-cyan-400',
  },
  {
    id: 'cat_clean',
    name: 'House & Deep Cleaning',
    slug: 'cleaner',
    iconName: 'Sparkles',
    description: 'Sofa, carpet, kitchen deep cleaning & full house wash',
    popularCount: 3100,
    badge: 'Top Choice',
    colorBg: 'bg-emerald-50 dark:bg-emerald-950/40',
    colorText: 'text-emerald-600 dark:text-emerald-400',
  },
  {
    id: 'cat_pest',
    name: 'Pest Control',
    slug: 'pest-control',
    iconName: 'ShieldAlert',
    description: 'Cockroach, termite, bed bug & mosquito extermination',
    popularCount: 950,
    colorBg: 'bg-rose-50 dark:bg-rose-950/40',
    colorText: 'text-rose-600 dark:text-rose-400',
  },
  {
    id: 'cat_appliance',
    name: 'Appliance Repair',
    slug: 'appliance-repair',
    iconName: 'Wrench',
    description: 'Refrigerator, washing machine, microwave & oven fix',
    popularCount: 1250,
    colorBg: 'bg-purple-50 dark:bg-purple-950/40',
    colorText: 'text-purple-600 dark:text-purple-400',
  },
  {
    id: 'cat_carp',
    name: 'Carpenter',
    slug: 'carpenter',
    iconName: 'Hammer',
    description: 'Furniture assembly, door lock repair, custom woodwork',
    popularCount: 820,
    colorBg: 'bg-orange-50 dark:bg-orange-950/40',
    colorText: 'text-orange-600 dark:text-orange-400',
  },
  {
    id: 'cat_paint',
    name: 'Painting & Waterproofing',
    slug: 'painter',
    iconName: 'Paintbrush',
    description: 'Interior wall paint, damp proofing & exterior coating',
    popularCount: 640,
    colorBg: 'bg-indigo-50 dark:bg-indigo-950/40',
    colorText: 'text-indigo-600 dark:text-indigo-400',
  },
  {
    id: 'cat_cctv',
    name: 'CCTV & Security System',
    slug: 'cctv',
    iconName: 'Camera',
    description: 'IP camera setup, DVR config & security monitoring',
    popularCount: 510,
    colorBg: 'bg-teal-50 dark:bg-teal-950/40',
    colorText: 'text-teal-600 dark:text-teal-400',
  },
  {
    id: 'cat_interior',
    name: 'Interior & Decor Design',
    slug: 'interior',
    iconName: 'LayoutGrid',
    description: 'False ceiling, modular kitchen & smart home setup',
    popularCount: 430,
    colorBg: 'bg-violet-50 dark:bg-violet-950/40',
    colorText: 'text-violet-600 dark:text-violet-400',
  },
];

export const FEATURED_SERVICES: ServiceItem[] = [
  {
    id: 'srv_1',
    title: 'AC Jet Cleaning & Master Servicing',
    slug: 'ac-jet-cleaning',
    categorySlug: 'ac-service',
    categoryName: 'AC Service',
    providerId: 'prov_apex',
    providerName: 'Apex Climate Care Ltd.',
    providerAvatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=120&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewCount: 320,
    price: 1200,
    originalPrice: 1500,
    priceUnit: 'per split unit',
    duration: '60 mins',
    image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&auto=format&fit=crop&q=80',
    badge: '20% OFF',
    features: ['High-pressure jet wash', 'Gas leakage check', '90-day warranty'],
    location: 'DOHS Mohakhali & Baridhara',
    description: 'Comprehensive high-pressure jet wash service for split AC units. Includes indoor blower unit wash, outdoor condenser coil cleaning, drain line unclogging, and gas pressure checkup.',
    addons: [
      { id: 'add_gas', title: 'R22/R410 Refrigerant Gas Top-Up', price: 800, description: 'Up to 50% gas pressure refill' },
      { id: 'add_filter', title: 'Antibacterial Anti-Allergen Filter Replacement', price: 450, description: 'Medical grade air filter' },
      { id: 'add_out', title: 'Outdoor Bracket Safety Reinforcement', price: 300, description: 'Anti-rust steel bracket fitting' },
    ],
  },
  {
    id: 'srv_2',
    title: 'Full House Deep Cleaning Package',
    slug: 'full-house-deep-clean',
    categorySlug: 'cleaner',
    categoryName: 'House Cleaning',
    providerId: 'prov_shine',
    providerName: 'ShineSheba Cleaning Pros',
    providerAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
    rating: 4.85,
    reviewCount: 512,
    price: 4500,
    originalPrice: 5500,
    priceUnit: 'up to 1500 sqft',
    duration: '4-5 hours',
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&auto=format&fit=crop&q=80',
    badge: 'Best Value',
    features: ['Kitchen & bath sanitization', 'Floor scrub & polish', 'Sofa vacuuming'],
    location: 'Dhaka Metropolitan',
    description: 'Deep cleaning using industrial grade vacuum cleaners and eco-friendly disinfectant solutions. Covers living room, bedrooms, kitchen oil grease scrubbing, and bathroom tile descaling.',
    addons: [
      { id: 'add_sofa', title: '5-Seater Sofa Shampoo Wash', price: 1200, description: 'Deep foam shampooing & stain removal' },
      { id: 'add_fridge', title: 'Refrigerator Interior Disinfection', price: 500, description: 'Odour removal & sanitization' },
    ],
  },
  {
    id: 'srv_3',
    title: 'Emergency Electrical & Circuit Repair',
    slug: 'emergency-electrical-fix',
    categorySlug: 'electrician',
    categoryName: 'Electrician',
    providerId: 'prov_volt',
    providerName: 'VoltFix Master Electricians',
    providerAvatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=120&auto=format&fit=crop&q=80',
    rating: 4.95,
    reviewCount: 418,
    price: 500,
    priceUnit: 'visiting charge',
    duration: '30 min arrival',
    image: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=600&auto=format&fit=crop&q=80',
    badge: '24/7 Available',
    features: ['Certified technicians', 'Safety check included', 'Upfront pricing'],
    location: 'DOHS Mohakhali & Baridhara',
    description: 'Fast response electrical diagnostics for circuit breaker trips, short circuit burning, main DB board repair, socket replacement, and chandelier fitting.',
    addons: [
      { id: 'add_mcb', title: 'Main MCB Circuit Breaker Replacement', price: 650, description: 'Genuine Schneider 32A MCB' },
      { id: 'add_fan', title: 'Ceiling Fan Regulator & Wiring Fix', price: 350, description: 'Noise fix & speed regulator' },
    ],
  },
  {
    id: 'srv_4',
    title: 'Kitchen & Bathroom Pipe Leak Fix',
    slug: 'plumbing-pipe-leak-fix',
    categorySlug: 'plumber',
    categoryName: 'Plumbing',
    providerId: 'prov_aqua',
    providerName: 'AquaFlow Plumbing Specialists',
    providerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewCount: 290,
    price: 600,
    originalPrice: 800,
    priceUnit: 'base service',
    duration: '45 mins',
    image: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=600&auto=format&fit=crop&q=80',
    badge: 'Fast Fix',
    features: ['High-tech leak detection', 'Genuine spare parts', 'Clean completion'],
    location: 'Mirpur & Gulshan',
    description: 'Professional plumbing diagnosis for concealed pipe leakages, basin tap repair, commode flush valve fitting, and line unclogging.',
    addons: [
      { id: 'add_tap', title: 'Brass Mixer Tap Installation', price: 400, description: 'Installation of hot & cold tap' },
      { id: 'add_filter_plumb', title: 'Water Purifier Line Connection', price: 350, description: 'T-joint fitting for aqua filters' },
    ],
  },
];

export const MOCK_PROVIDER_PROFILES: Record<string, ProviderProfile> = {
  prov_apex: {
    id: 'prov_apex',
    name: 'Apex Climate Care Ltd.',
    categorySlug: 'ac-service',
    categoryName: 'AC Service & Repair',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=1000&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewCount: 320,
    completedJobs: 1450,
    experienceYears: 8,
    isVerified: true,
    phone: '+880 1711-998877',
    email: 'contact@apexclimate.com',
    address: 'Shop 12, DOHS Shopping Complex, Mohakhali, Dhaka',
    bio: 'Apex Climate Care is the premier HVAC and air conditioning service provider operating in Mohakhali, Baridhara, Mirpur & Banani DOHS. We specialize in high-pressure jet wash, eco-friendly gas refills, compressor repair, and inverter AC troubleshooting.',
    specialties: ['High Pressure Jet Wash', 'R32/R410 Gas Refill', 'Inverter PCB Board Repair', 'Multi-split Ducting'],
    galleryImages: [
      'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=500&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1581094288338-2314dddb7ece?w=500&auto=format&fit=crop&q=80',
    ],
    services: [FEATURED_SERVICES[0]],
    reviews: [
      {
        id: 'rev_1',
        userName: 'Lt Col (Retd) Tariq Ahmed',
        userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
        rating: 5,
        date: '2 days ago',
        comment: 'Extremely professional technician! Arrived sharp on time at my DOHS residence. Cleaned the jet wash without leaving a single drop on hardwood floor.',
        serviceTitle: 'AC Jet Cleaning & Master Servicing',
      },
      {
        id: 'rev_2',
        userName: 'Dr. Shahana Parveen',
        userAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&auto=format&fit=crop&q=80',
        rating: 4.8,
        date: '1 week ago',
        comment: 'Great service. Refilled gas and fixed the water leakage problem instantly. Highly recommended for DOHS residents.',
        serviceTitle: 'AC Gas Refill & Cooling Check',
      },
    ],
  },
  prov_shine: {
    id: 'prov_shine',
    name: 'ShineSheba Cleaning Pros',
    categorySlug: 'cleaner',
    categoryName: 'House & Deep Cleaning',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1000&auto=format&fit=crop&q=80',
    rating: 4.85,
    reviewCount: 512,
    completedJobs: 2100,
    experienceYears: 6,
    isVerified: true,
    phone: '+880 1812-445566',
    email: 'info@shinesheba.com',
    address: 'House 45, Road 2, Mirpur DOHS, Dhaka',
    bio: 'ShineSheba is a dedicated residential deep cleaning service. Equipped with industrial steam cleaners, HEPA vacuum filters, and hospital-grade sanitizers.',
    specialties: ['Full House Scrubbing', 'Sofa & Carpet Steam Cleaning', 'Kitchen Grease Removal', 'Tile & Marble Polish'],
    galleryImages: [
      'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=500&auto=format&fit=crop&q=80',
    ],
    services: [FEATURED_SERVICES[1]],
    reviews: [
      {
        id: 'rev_3',
        userName: 'Major (Retd) Kabir',
        userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
        rating: 5,
        date: '3 days ago',
        comment: 'Very polite team. Made my 1800 sqft apartment shine like new before Eid family gathering.',
        serviceTitle: 'Full House Deep Cleaning Package',
      },
    ],
  },
  prov_volt: {
    id: 'prov_volt',
    name: 'VoltFix Master Electricians',
    categorySlug: 'electrician',
    categoryName: 'Electrician',
    avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=1000&auto=format&fit=crop&q=80',
    rating: 4.95,
    reviewCount: 418,
    completedJobs: 3200,
    experienceYears: 10,
    isVerified: true,
    phone: '+880 1913-778899',
    email: 'support@voltfix.com',
    address: 'Road 7, Baridhara DOHS, Dhaka',
    bio: 'VoltFix provides 24/7 emergency electrical repair, DB box installation, short circuit fix, chandelier mounting, and generator auto-transfer switch setup.',
    specialties: ['24/7 Emergency Fix', 'DB Box & MCB Wiring', 'Chandelier Mounting', 'Smart Switch & IoT Setup'],
    galleryImages: [
      'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=500&auto=format&fit=crop&q=80',
    ],
    services: [FEATURED_SERVICES[2]],
    reviews: [
      {
        id: 'rev_4',
        userName: 'Ayesha Siddiqua',
        userAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80',
        rating: 5,
        date: '5 days ago',
        comment: 'Fixed short circuit problem in middle of night! Extremely prompt and safe work.',
        serviceTitle: 'Emergency Electrical & Circuit Repair',
      },
    ],
  },
  prov_aqua: {
    id: 'prov_aqua',
    name: 'AquaFlow Plumbing Specialists',
    categorySlug: 'plumber',
    categoryName: 'Plumbing',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=1000&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewCount: 290,
    completedJobs: 1800,
    experienceYears: 7,
    isVerified: true,
    phone: '+880 1715-223344',
    email: 'info@aquaflow.com',
    address: 'Road 10, Mohakhali DOHS, Dhaka',
    bio: 'AquaFlow offers complete residential plumbing solutions including pipe leak detection, water pump servicing, sanitary fixture installation, and line unclogging.',
    specialties: ['Pipe Leak Repair', 'Water Tank & Pump Service', 'Sanitary Ware Installation', 'Drain Line Jet Unclog'],
    galleryImages: [
      'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=500&auto=format&fit=crop&q=80',
    ],
    services: [FEATURED_SERVICES[3]],
    reviews: [],
  },
};
